name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c  "chmod 777 /srv/jekyll && jekyll -v"

#name: Build and deploy jekyll site
#
#on:
#  push:
#    branches:
#      - master
#      # - source
#      # It is highly recommended that you only run this action on push to a
#        # specific branch, eg. master or source (if on *.github.io repo)
#
#jobs:
#  jekyll:
#    runs-on: ubuntu-16.04 # can change this to ubuntu-latest if you prefer
#    steps:
#      - name: ğŸ“‚ setup
#        uses: actions/checkout@v2
#        # include the lines below if you are using jekyll-last-modified-at
#        # or if you would otherwise need to fetch the full commit history
#        # however this may be very slow for large repositories!
#        # with:
#          # fetch-depth: '0'
#
#      - name: ğŸ“ cache bundler files
#        uses: actions/cache@v1
#        with:
#          path: vendor/bundle
#          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-gems-
#
#      - name: ğŸ’ setup ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.6 # can change this to 2.7 or whatever version you prefer
#
#      - name: ğŸ”¨ install dependencies & build site
#        uses: limjh16/jekyll-action-ts@v2
